[project]
name = "test-vbai-uv"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "keras>=3.6.0",
    "matplotlib>=3.9.2",
    "tensorflow-datasets>=4.9.6",
    "tensorflow>=2.17.0",
]
