[project]
name = "test-vbai-uv"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = [
    "keras>=3.6.0",
    "matplotlib>=3.9.2",
    "numpy>=1.26.4",
    "pyqt5>=5.15.11",
    "signxai>=1.1.5",
    "tensorflow-datasets>=4.9.6",
    "tensorflow>=2.17.0",
]
